### ISSUE TITLE
Cannot get the url information

### ISSUE THREAD

**Issue by rlee1990** [muehlemann/GiphyLibrary#2]
When trying to get the results it will not display the url information. Does this work in fragments?

**Comment by muehlemann** [comment]
Yes, this does work in fragments. Can you please provide more context to your issue.

**Comment by rlee1990** [comment]
First thanks for the quick reply. When I try to log the result. I get nothing.
`override fun onGiphySelected(url: String?) {
        println("Gif: $url")
    }`

Here is my on result and so on:

`giphyLibrary.onActivityResult(requestCode, resultCode, data)
fun showGif() {
        giphyLibrary.start(this@ChatViewFragment.activity, this, apiKey)
    }
val giphyLibrary = GiphyLibrary()`

**Comment by muehlemann** [comment]
Just to clarify is the output in your logs `Gif: ` or are you not getting anything at all?

**Comment by rlee1990** [comment]
Correct nothing at all.

**Comment by muehlemann** [comment]
I see, it seems like the `onActivityResult` is delegated to the activity instead of the fragment. To fix your issue I recommend starting the GiphyActivity with a custom intent like so:

```
// set the listener
giphyLibrary.listener = this;

// start the activity
Intent intent = new Intent(getActivity(), GiphyActivity.class);
intent.putExtra(GiphyLibrary.API_KEY, apiKey);
startActivityForResult(intent, GiphyLibrary.REQUEST_CODE);
```

This way the activity result will delegate to your fragment instead of the activity. 

Let me know if that works for you. I will also publish a patch to fix this issue within the week.

**Comment by rlee1990** [comment]
Thanks ill give it a try

**Comment by rlee1990** [comment]
That worked thanks again. Really saved me from having to make this from scratch.

**Comment by muehlemann** [comment]
Glad it worked! I'm going to close this issue and release a fix within the week. Cheers!
